stages:
  - build
  - deploy

build:
  stage: build
  image: node:23.3.0
  cache:
    paths:
      - node_modules/
  script:
    - echo "Building deploy package"
    - npm install
    - npm run build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
      - build/

pages:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying to server"
    - rm -rf public
    - mv build public
    - echo "Deployed"
  artifacts:
    paths:
      - public
  only:
    - master