# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM packages...
      - npm install
      
  build:
    # TODO : for normal publishing of new episodes, we should not build the site, just run toucan.
    commands:
      - echo Build started on `date`
      - npm run build
      - ls -al build
      - npm run copy
      - toucan generate ./toucan ./dist

  post_build:
    commands:
      - echo Build completed on `date`, publishing to AWS Developers Podcast will be done by the pipeline.
      # - aws s3 sync _site/ s3://stormacq.com
      - echo $CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - '**/*'
  name: adp-$(date +%Y%m%d)
  base-directory: 'dist'
