# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM packages...
      - npm install
      
  build:
    # TODO : for normal publishing of new episodes, we should not build the site, just run toucan.
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run copy
      - toucan generate ./toucan ./dist

  post_build:
    commands:
      - echo "Build $CODEBUILD_BUILD_NUMBER completed on `date`, publishing to AWS Developers Podcast will be done by the pipeline."

artifacts:
  files:
    - '**/*'
  name: adp-$(date +%Y%m%d%H%M%S).zip
  base-directory: 'dist'
